### ISSUE TITLE
Cannot access upload_url output property

### ISSUE THREAD

**Issue by fiddlermikey** [kaliber5/action-get-release#71]
I am considering using this action to simply pull the latest release upload_url for another task. When I try to use it, all output properties are visible except for the one I need.

Here is the workflow:

```
name: Get Latest Release
on: [push, repository_dispatch, workflow_dispatch]

jobs:
  build:
    name: FindLatestRelease
    runs-on: windows-latest
    steps:
      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token}}
          latest: true
          #owner: fiddlermikey
          #repo: githubscripting
      - name: Echo Values
        run: |
          echo "ID: ${{ steps.latest_release.outputs.id}}"
          echo "URL: ${{ steps.latest_release.outputs.url}}"
          echo "HTML URL: ${{ steps.latest_release.outputs.html_url}}"
          echo "Assets URL: ${{ steps.latest_release.outputs.assets_url}}"
          echo "upload_url: ${{ steps.latest_release.output.upload_url}}"
          echo "Name: ${{ steps.latest_release.outputs.name}}"
          echo "Tag: ${{ steps.latest_release.outputs.tag_name}}"
   ```

And the Log/results: (note the missing upload_url property)

ID: 70912854
URL: https://api.github.com/repos/fiddlermikey/githubscripting/releases/70912854
HTML URL: https://github.com/fiddlermikey/githubscripting/releases/tag/1.0.0
Assets URL: https://api.github.com/repos/fiddlermikey/githubscripting/releases/70912854/assets
upload_url:                                                                                                                                             
Name: 1.0.0
Tag: 1.0.0
